//! Cross-implementation tests against the Python reference.
//!
//! `tests/vectors.json` is generated by `tools/gen_vectors.py` running against
//! `genesis_mesh` itself. These tests assert that this crate reproduces those
//! bytes exactly. If Python's canonical form ever changes, regenerate the file
//! and these tests fail loudly instead of the two implementations drifting
//! apart and only failing later, in production, as unverifiable signatures.

use genesis_mesh::canonical;
use genesis_mesh::crypto::{self, KeyPair};
use serde_json::Value;

fn vectors() -> Value {
    let raw = include_str!("vectors.json");
    serde_json::from_str(raw).expect("vectors.json is valid JSON")
}

/// The canonical form we produce must match Python's byte for byte.
///
/// Re-canonicalising Python's own output is a fixed-point check: parsing the
/// string back to a `Value` and re-emitting it must return the identical bytes.
#[test]
fn canonical_form_matches_python() {
    let v = vectors();
    let cases = v["cases"].as_array().expect("cases array");
    assert!(!cases.is_empty(), "vectors.json has no cases");

    for case in cases {
        let name = case["name"].as_str().unwrap();
        let expected = case["canonical_json"].as_str().unwrap();

        let parsed: Value = serde_json::from_str(expected)
            .unwrap_or_else(|e| panic!("case {name}: python output did not parse: {e}"));
        let actual = canonical::canonicalize(&parsed);

        assert_eq!(
            actual, expected,
            "case {name}: canonical form diverged from the Python reference"
        );
    }
}

/// Signatures produced by Python must verify here, over those same bytes.
#[test]
fn python_signatures_verify() {
    let v = vectors();
    let public_key = v["public_key_b64"].as_str().expect("public_key_b64");

    for case in v["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let payload = case["canonical_json"].as_str().unwrap();
        let signature = case["signature_b64"].as_str().unwrap();

        let ok = crypto::verify_b64(payload.as_bytes(), signature, public_key)
            .unwrap_or_else(|e| panic!("case {name}: {e}"));
        assert!(ok, "case {name}: Python signature failed to verify in Rust");
    }
}

/// Signing the same bytes with the same seed must reproduce Python's signature.
///
/// Ed25519 is deterministic, so this is an equality check rather than a
/// verification. It catches a whole class of key-loading bugs: if we ever
/// misinterpreted the seed encoding, verification alone would still pass while
/// producing signatures Python could not check.
#[test]
fn rust_reproduces_python_signatures() {
    let v = vectors();
    let seed = v["signing_key_seed_b64"].as_str().expect("seed");
    let keypair = KeyPair::from_seed_b64(seed).expect("seed loads");

    assert_eq!(
        keypair.public_key_b64(),
        v["public_key_b64"].as_str().unwrap(),
        "public key derived from the seed does not match Python's"
    );

    for case in v["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let payload = case["canonical_json"].as_str().unwrap();
        let expected = case["signature_b64"].as_str().unwrap();

        assert_eq!(
            keypair.sign_b64(payload.as_bytes()),
            expected,
            "case {name}: signature bytes differ from Python's"
        );
    }
}

/// Documents from Python must deserialise, re-serialise, and still verify.
///
/// This is the round trip that matters in practice: a certificate issued by the
/// Python Network Authority, parsed by a Rust node, must still verify after the
/// Rust node has held it in its own types.
#[test]
fn round_trip_through_rust_types_preserves_signatures() {
    use genesis_mesh::models::{
        CertificateRevocationList, JoinCertificate, ServiceManifest, Signed,
    };

    let v = vectors();
    let public_key = v["public_key_b64"].as_str().unwrap();
    let seed = v["signing_key_seed_b64"].as_str().unwrap();
    let keypair = KeyPair::from_seed_b64(seed).unwrap();

    for case in v["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let payload = case["canonical_json"].as_str().unwrap();
        let signature = case["signature_b64"].as_str().unwrap();

        // Attach Python's signature to the Rust-parsed document, then confirm
        // the signing input we compute still matches what Python signed.
        let recomputed = if name.starts_with("join_certificate") {
            let mut doc: JoinCertificate =
                serde_json::from_str(payload).unwrap_or_else(|e| panic!("case {name}: parse: {e}"));
            doc.signatures.clear();
            doc.signing_input().unwrap()
        } else if name == "service_manifest" {
            let doc: ServiceManifest =
                serde_json::from_str(payload).unwrap_or_else(|e| panic!("case {name}: parse: {e}"));
            doc.signing_input().unwrap()
        } else if name == "crl" {
            let doc: CertificateRevocationList =
                serde_json::from_str(payload).unwrap_or_else(|e| panic!("case {name}: parse: {e}"));
            doc.signing_input().unwrap()
        } else {
            panic!("case {name}: no Rust type mapped; add one to this test");
        };

        assert_eq!(
            recomputed, payload,
            "case {name}: round trip through Rust types changed the signing input"
        );
        assert!(
            crypto::verify_b64(recomputed.as_bytes(), signature, public_key).unwrap(),
            "case {name}: signature no longer verifies after round trip"
        );
        assert_eq!(keypair.sign_b64(recomputed.as_bytes()), signature);
    }
}
