#!/usr/bin/env bash
# Run AFTER the one-time host steps:
#   cloudflared tunnel login
#   cloudflared tunnel create genesis-mesh-gateway
#   cloudflared tunnel route dns genesis-mesh-gateway <hostname>
#
# Usage: bash cloudflared/finish-setup.sh <hostname> [tunnel-name]
set -euo pipefail

HOSTNAME="${1:?usage: finish-setup.sh <hostname> [tunnel-name]}"
TUNNEL_NAME="${2:-genesis-mesh-gateway}"
HERE="$(cd "$(dirname "$0")" && pwd)"
CF_DIR="${CLOUDFLARED_HOME:-$HOME/.cloudflared}"

# Resolve the tunnel UUID from `cloudflared tunnel list`.
UUID="$(cloudflared tunnel list --output json \
  | python -c "import sys,json; \
      t=[x for x in json.load(sys.stdin) if x['name']=='${TUNNEL_NAME}']; \
      print(t[0]['id'] if t else '')")"
[ -n "$UUID" ] || { echo "tunnel '${TUNNEL_NAME}' not found — run 'cloudflared tunnel create ${TUNNEL_NAME}'"; exit 1; }
echo "tunnel ${TUNNEL_NAME} = ${UUID}"

# Stage the credentials file the connector authenticates with.
chmod +w "${HERE}/credentials.json" 2>/dev/null || true
cp "${CF_DIR}/${UUID}.json" "${HERE}/credentials.json"
echo "copied credentials -> cloudflared/credentials.json"

# Render config.yml.
cat > "${HERE}/config.yml" <<YAML
# Generated by finish-setup.sh — locally-managed Cloudflare tunnel.
tunnel: ${UUID}
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: ${HOSTNAME}
    service: http://gateway:8080
  - service: http_status:404
YAML
echo "wrote config.yml (hostname: ${HOSTNAME})"

cd "${HERE}/.."
docker compose up -d --build
echo
docker compose ps
echo
echo "Public endpoint: https://${HOSTNAME}/health"
