"""Regenerate tests/vectors.json from the Python reference implementation.

Run from the genesismesh repo so `genesis_mesh` is importable:

    cd C:/Source/GenesisMeshLabs/genesismesh
    python ../rust/tools/gen_vectors.py

The Rust interop tests assert byte-for-byte against this file. If the Python
canonical form ever changes, regenerate here and the Rust tests will fail
loudly rather than drifting silently.
"""

import base64
import json
from datetime import datetime, timezone
from pathlib import Path

import sys

# Make `genesis_mesh` importable however this script is invoked: running
# `python tools/gen_vectors.py` puts THIS file's directory on sys.path, not
# the caller's cwd, so point at the sibling genesismesh checkout explicitly.
_REPO = Path(__file__).resolve().parents[2] / "genesismesh"
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

import nacl.signing

from genesis_mesh.crypto.signing import sign_data
from genesis_mesh.models.certificates import JoinCertificate, ServiceManifest
from genesis_mesh.models.revocation import CertificateRevocationList, RevokedCertificate

SEED = bytes(range(32))
SK = nacl.signing.SigningKey(SEED)
PUB = base64.b64encode(bytes(SK.verify_key)).decode()

UTC = timezone.utc


def entry(name, model, note=""):
    canonical = model.to_canonical_json()
    return {
        "name": name,
        "note": note,
        "canonical_json": canonical,
        "signature_b64": sign_data(canonical.encode("utf-8"), SK),
    }


vectors = {
    "_comment": "Generated by tools/gen_vectors.py from the Python reference implementation. Do not hand-edit.",
    "signing_key_seed_b64": base64.b64encode(SEED).decode(),
    "public_key_b64": PUB,
    "cases": [
        entry(
            "join_certificate_basic",
            JoinCertificate(
                cert_id="cert-001",
                node_public_key=PUB,
                network_name="mesh-alpha",
                roles=["role:anchor", "role:client"],
                issued_at=datetime(2026, 1, 1, 12, 0, 0, tzinfo=UTC),
                expires_at=datetime(2026, 1, 8, 12, 0, 0, tzinfo=UTC),
                issued_by="na-001",
            ),
            "keys must sort alphabetically; no whitespace",
        ),
        entry(
            "join_certificate_non_ascii",
            JoinCertificate(
                cert_id="cert-002",
                node_public_key=PUB,
                network_name="mesh-tëst-\u00e5\u00e4\u00f6",
                roles=[],
                issued_at=datetime(2026, 1, 1, 12, 0, 0, tzinfo=UTC),
                expires_at=datetime(2026, 1, 8, 12, 0, 0, tzinfo=UTC),
                issued_by="na-001",
            ),
            "non-ASCII MUST be \\uXXXX escaped (Python ensure_ascii=True); serde_json does not do this by default",
        ),
        entry(
            "join_certificate_astral",
            JoinCertificate(
                cert_id="cert-003",
                node_public_key=PUB,
                network_name="mesh-\U0001F510",
                roles=["role:client"],
                issued_at=datetime(2026, 1, 1, 12, 0, 0, tzinfo=UTC),
                expires_at=datetime(2026, 1, 8, 12, 0, 0, tzinfo=UTC),
                issued_by="na-001",
            ),
            "astral-plane codepoint must become a UTF-16 surrogate pair",
        ),
        entry(
            "join_certificate_subsecond",
            JoinCertificate(
                cert_id="cert-004",
                node_public_key=PUB,
                network_name="mesh-alpha",
                roles=["role:anchor"],
                issued_at=datetime(2026, 1, 1, 12, 0, 0, 123456, tzinfo=UTC),
                expires_at=datetime(2026, 1, 8, 12, 30, 45, 500000, tzinfo=UTC),
                issued_by="na-001",
            ),
            "pins the sub-second datetime rendering",
        ),
        entry(
            "service_manifest",
            ServiceManifest(
                service_name="svc-directory",
                service_key=PUB,
                endpoints=["https://a.example:8443", "https://b.example:8443"],
                issued_at=datetime(2026, 1, 1, 12, 0, 0, tzinfo=UTC),
                valid_to=datetime(2026, 2, 1, 12, 0, 0, tzinfo=UTC),
                issued_by="na-001",
            ),
            "array ordering is preserved, not sorted",
        ),
        entry(
            "crl",
            CertificateRevocationList(
                crl_id="crl-001",
                sequence=7,
                issued_at=datetime(2026, 1, 5, 0, 0, 0, tzinfo=UTC),
                next_update=datetime(2026, 1, 6, 0, 0, 0, tzinfo=UTC),
                issuer="na-001",
                revoked_certificates=[
                    RevokedCertificate(
                        certificate_id="cert-001",
                        revoked_at=datetime(2026, 1, 4, 9, 30, 0, tzinfo=UTC),
                        reason="key_compromise",
                        issuer="na-001",
                    )
                ],
            ),
            "nested objects sort their keys too",
        ),
    ],
}

out = Path(__file__).resolve().parent.parent / "tests" / "vectors.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(vectors, indent=2) + "\n", encoding="utf-8")
print(f"wrote {out} ({len(vectors['cases'])} cases)")
