import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createPrivateKey, createPublicKey, verify} from 'node:crypto';
import {execFileSync} from 'node:child_process';
const source=readFileSync(new URL('../ui/signing.js',import.meta.url),'utf8');
const {canonical,operatorHeaders}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const body={subject_id:'gateway-å-😀',roles:['member'],nested:{'😀':true,'\ue000':null},count:12};
const python=execFileSync('python',['-X','utf8','-c','import sys,json; print(json.dumps(json.load(sys.stdin),sort_keys=True,separators=(",",":")))'],{input:JSON.stringify(body),encoding:'utf8'}).trim();
assert.equal(canonical(body),python);
for(const n of [1.5,Number.MAX_SAFE_INTEGER+1,NaN,Infinity])assert.throws(()=>canonical({n}));
const seed=Buffer.alloc(32,7), keyId='test-operator';
const headers=await operatorHeaders(body,seed.toString('base64'),keyId);
const envelope={body,key_id:keyId,timestamp:headers['X-Admin-Timestamp'],nonce:headers['X-Admin-Nonce']};
const expected=execFileSync('python',['-X','utf8','-c','import sys,json; print(json.dumps(json.load(sys.stdin),sort_keys=True,separators=(",",":")))'],{input:JSON.stringify(envelope),encoding:'utf8'}).trim();
const key=createPrivateKey({key:Buffer.concat([Buffer.from('302e020100300506032b657004220420','hex'),seed]),format:'der',type:'pkcs8'});
assert(verify(null,Buffer.from(expected),createPublicKey(key),Buffer.from(headers['X-Admin-Signature'],'base64')));
await assert.rejects(()=>operatorHeaders({},'invalid','test'));
assert(!JSON.stringify(headers).includes(seed.toString('base64')));
console.log('Browser signing matches Python canonical JSON and Ed25519 verification; unsafe numeric inputs rejected.');
