'use strict';
const $ = id => document.getElementById(id);
const endpoints = [
  {method:'GET',path:'/health',name:'Liveness',description:'Check whether the gateway process is running.',public:true},
  {method:'GET',path:'/ready',name:'Trust readiness',description:'Check whether every configured network has a fresh revocation snapshot.',public:true},
  {method:'GET',path:'/api',name:'Service information',description:'Inspect the gateway version, mode and API endpoints.',public:true},
  {method:'GET',path:'/v1/networks',name:'Network data',description:'View only the trust domains authorized for your service identity.'},
  {method:'POST',path:'/verify',name:'Verify certificate',description:'Evaluate a Genesis Mesh join certificate against operator-controlled trust policy.',body:{certificate:{}}},
  {method:'POST',path:'/verify/batch',name:'Verify batch',description:'Evaluate a bounded batch of certificates. Inspect trusted on every result.',body:{certificates:[]}},
  {method:'GET',path:'/metrics',name:'Service metrics',description:'Read Prometheus metrics. Your service identity needs metrics permission.'}
];
let selected=endpoints[0];
function choose(e) { selected=e; $('method').textContent=e.method; $('method').className='method '+e.method.toLowerCase(); $('path').textContent=e.path; $('description').textContent=e.description; $('auth-label').textContent=e.public?'Public':'Bearer token'; $('body-field').hidden=!e.body; if(e.body)$('request-body').value=JSON.stringify(e.body,null,2); for(const b of $('endpoints').children)b.classList.toggle('selected',b.dataset.path===e.path); }
for(const e of endpoints){const b=document.createElement('button'); b.type='button'; b.dataset.path=e.path; const method=document.createElement('span');method.className='method '+e.method.toLowerCase();method.textContent=e.method;const label=document.createElement('span');const code=document.createElement('code');code.textContent=e.path;const small=document.createElement('small');small.textContent=e.name;label.append(code,small);b.append(method,label);b.addEventListener('click',()=>choose(e));$('endpoints').append(b);}choose(selected);
async function request(path, options={}) { const response=await fetch(path,{...options,cache:'no-store',credentials:'omit',redirect:'error',signal:AbortSignal.timeout(20000)});const raw=await response.text();let data;try{data=JSON.parse(raw);}catch{data=raw;}return {response,data}; }
async function send(){const e=selected;const headers={};const token=$('token').value.trim();if(!e.public&&!token){$('request-state').textContent='Enter a service token for this endpoint.';return;}if(!e.public)headers.Authorization='Bearer '+token;let body;if(e.body){try{body=JSON.stringify(JSON.parse($('request-body').value));}catch{$('request-state').textContent='The request body must be valid JSON.';return;}headers['Content-Type']='application/json';} $('send').disabled=true;$('request-state').textContent='Sending…';const start=performance.now();try{const {response,data}=await request(e.path,{method:e.method,headers,body});$('response').textContent=typeof data==='string'?data:JSON.stringify(data,null,2);$('response-meta').textContent=response.status+' · '+Math.round(performance.now()-start)+' ms';$('request-state').textContent=response.ok?'Request completed':'Request rejected ('+response.status+')';$('request-id').textContent='Request ID: '+(response.headers.get('x-request-id')||'unavailable');if(e.path==='/v1/networks'&&response.ok)renderNetworks(data);}catch{$('request-state').textContent='Cannot reach the gateway. Check your connection and retry.';$('response-meta').textContent='Connection failed';}finally{$('send').disabled=false;}}
function renderNetworks(data){const container=$('network-data');container.replaceChildren();container.className='network-list';if(!data.networks?.length){container.textContent='No networks are assigned to this service identity.';return;}for(const n of data.networks){const card=document.createElement('article');const title=document.createElement('h3');title.textContent=n.name;const status=document.createElement('span');status.className='pill';status.textContent=n.ready?'Ready':'Stale revocation data';const pre=document.createElement('pre');pre.textContent=JSON.stringify({authorities:n.anchors,required_roles:n.required_roles,revocation:n.revocation},null,2);card.append(title,status,pre);container.append(card);}}
$('send').addEventListener('click',send);$('clear-token').addEventListener('click',()=>{$('token').value='';$('response').textContent='Session data cleared.';$('request-id').textContent='';$('network-data').replaceChildren();$('network-data').textContent='Enter a service token and load your networks.';});$('load-networks').addEventListener('click',()=>{choose(endpoints.find(e=>e.path==='/v1/networks'));send();});
async function refresh(){try{const results=await Promise.all([request('/health'),request('/ready'),request('/api')]);const health=results[0].response.ok;const ready=results[1].response.ok;$('health-value').textContent=health?'Operational':'Unavailable';$('health-detail').textContent='Checked '+new Date().toLocaleTimeString();$('ready-value').textContent=ready?'Ready':'Not ready';$('connection').textContent=health?'Gateway connected':'Gateway unavailable';$('connection-dot').classList.toggle('bad',!health);$('version').textContent='v'+(results[2].data.version||'?');}catch{$('health-value').textContent='Unavailable';$('ready-value').textContent='Unknown';$('connection').textContent='Connection unavailable';$('connection-dot').classList.add('bad');}}
refresh();setInterval(()=>{if(!document.hidden)refresh();},30000);
